#!/usr/bin/env python

import rospy

import tf2_ros
from cartpole.msg import Data




class Cam():
    def __init__(self):
        
        self.buf = tf2_ros.Buffer()
        self.listen = tf2_ros.TransformListener(self.buf)
        self.timer = rospy.Timer(rospy.Duration(1./12),self.timer_callback)
  
        self.data_x_pub = rospy.Publisher('/x_data', Data, queue_size=10000)
        self.data_xvel_pub = rospy.Publisher('/xdot_data', Data, queue_size=10000)
        
        self.data_y_pub = rospy.Publisher('/y_data', Data, queue_size=10000)
        self.data_yvel_pub = rospy.Publisher('/ydot_data', Data, queue_size=10000)

        self.timer_data = rospy.Timer(rospy.Duration(1./280), self.timer_data_callback)

        self.x = 0.
        self.x_old = 0.
        self.x_first = 0.
        
        self.y = 0.
        self.y_old = 0.
        self.y_first = 0.
        
        self.xdot = 0.
        self.ydot = 0.
        
        self.first = True
        
    
        

    def timer_callback(self,event):
        """
        Callback for getting camera data
        Args:
            None
        """ 
        try:
            query = self.buf.lookup_transform("camera_color_optical_frame", "tag_10", rospy.Time())
            
            if self.first:
                self.x_first = query.transform.translation.x
                self.first = False
                self.y_first = query.transform.translation.y
            
            self.y_old = self.y
            self.x_old = self.x  
            self.x = query.transform.translation.x - self.x_first
            self.y = query.transform.translation.y - self.y_first
            self.xdot = (self.x-self.x_old)/(1./12.)
            self.ydot = (self.y - self.y_old)/(1./12.)
            
        except:
            print('april tag transform not available')
        print('x:', self.x)
        print('xdot:', self.xdot)
        print('y:', -self.y)
        print('ydot:', -self.ydot)
        
    def timer_data_callback(self, event):
        """X, Y data publisher 

        Args:
            None
        """
        self.data_y_pub.publish(-self.y)
        self.data_yvel_pub.publish(-self.ydot)
        
        self.data_x_pub.publish(self.x)
        self.data_xvel_pub.publish(self.xdot)
    

        
               
        
        

                
def main():
    """
    Main function
    """
    rospy.init_node('rsense')
    cam = Cam()
    rospy.spin()

if __name__ == '__main__':
    main()